//! Group A.3/A.4: decode REAL TypeScript-SDK serialized bytes.
//!
//! Fixtures in `fixtures/ts_serialization.json` are generated by `fixtures/gen_ts_fixtures.mjs`
//! using the same `superjson` library the DBOS TypeScript SDK (4.21.x) uses, wrapped exactly as
//! `ts/src/serialization.ts`'s `DBOSJSON` does. Regenerate with:
//!   (cd .context/ts-fixtures && npm i superjson@2 && node gen.mjs)

use std::collections::{BTreeMap, HashMap};

use dbos::serialize::decode_value;
use serde::Deserialize;
use serde_json::{json, Value};

fn fixtures() -> HashMap<String, String> {
    serde_json::from_str(include_str!("fixtures/ts_serialization.json")).unwrap()
}

#[test]
fn decodes_real_ts_superjson_bytes() {
    let f = fixtures();
    let sj = Some("js_superjson");

    // Scalars / containers pass through.
    assert_eq!(decode_value::<i64>(Some(&f["sj_int"]), sj).unwrap(), 42);
    assert_eq!(
        decode_value::<String>(Some(&f["sj_string"]), sj).unwrap(),
        "hello"
    );
    assert!(decode_value::<bool>(Some(&f["sj_bool"]), sj).unwrap());
    assert_eq!(
        decode_value::<Option<i64>>(Some(&f["sj_null"]), sj).unwrap(),
        None
    );
    assert_eq!(
        decode_value::<Vec<i64>>(Some(&f["sj_array"]), sj).unwrap(),
        vec![1, 2, 3]
    );
    assert_eq!(
        decode_value::<Value>(Some(&f["sj_object"]), sj).unwrap(),
        json!({"a":1,"b":{"c":"x"},"d":[true,null]})
    );

    // Rich JS types lower to JSON-native equivalents.
    // Date -> ISO string.
    assert_eq!(
        decode_value::<String>(Some(&f["sj_date"]), sj).unwrap(),
        "2024-01-02T03:04:05.000Z"
    );
    // BigInt -> number (here larger than 2^53, exact in i64).
    assert_eq!(
        decode_value::<i64>(Some(&f["sj_bigint"]), sj).unwrap(),
        9007199254740993
    );
    // Map -> object.
    let m: BTreeMap<String, i64> = decode_value(Some(&f["sj_map"]), sj).unwrap();
    assert_eq!(
        m,
        BTreeMap::from([("a".to_string(), 1), ("b".to_string(), 2)])
    );
    // Set -> array.
    assert_eq!(
        decode_value::<Vec<i64>>(Some(&f["sj_set"]), sj).unwrap(),
        vec![1, 2, 3]
    );

    // Nested rich types.
    #[derive(Debug, PartialEq, Deserialize)]
    struct WhenN {
        when: String,
        n: i64,
    }
    assert_eq!(
        decode_value::<WhenN>(Some(&f["sj_object_with_date"]), sj).unwrap(),
        WhenN {
            when: "2024-01-02T03:04:05.000Z".to_string(),
            n: 5
        }
    );

    // undefined -> null (None).
    #[derive(Debug, PartialEq, Deserialize)]
    struct AB {
        a: i64,
        b: Option<i64>,
    }
    assert_eq!(
        decode_value::<AB>(Some(&f["sj_undefined_field"]), sj).unwrap(),
        AB { a: 1, b: None }
    );
}

#[test]
fn decodes_legacy_dbosjson_rows_with_null_serialization() {
    // Legacy `DBOSJSON` rows (older TS DBs) have `serialization = NULL`; decoded via the
    // best-effort `None` fallback (must NOT be base64-decoded).
    let f = fixtures();

    assert_eq!(
        decode_value::<i64>(Some(&f["legacy_int"]), None).unwrap(),
        42
    );

    #[derive(Debug, PartialEq, Deserialize)]
    struct When {
        when: String,
    }
    assert_eq!(
        decode_value::<When>(Some(&f["legacy_object_with_date"]), None).unwrap(),
        When {
            when: "2024-01-02T03:04:05.000Z".to_string()
        }
    );

    #[derive(Debug, PartialEq, Deserialize)]
    struct Big {
        big: i64,
    }
    assert_eq!(
        decode_value::<Big>(Some(&f["legacy_object_with_bigint"]), None).unwrap(),
        Big {
            big: 123456789012345
        }
    );
}
